
sudo: required

services:
- docker

before_install:
- docker build -t bear2u/docker-react -f Dockerfile.dev .

script:
- docker run bear2u/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "docker-react2-env.pbzin8ceqc.ap-northeast-2"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

